version: '3'

services:

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./web/nginx/ssl/certs:/etc/nginx/ssl
      - ./web/nginx/config/fragments:/etc/nginx/fragments
      - ./web/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./web/log/nginx:/var/log/nginx
      - ./../src:/var/www/html
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - postgres
      - php
      - adminer

  php:
    container_name: php
    restart: unless-stopped
    build:
      context: ./../
      dockerfile: ./docker/web/php/Dockerfile
    volumes:
      - ./../src:/var/www/html
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '2345:5432'
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
      interval: 30s
      timeout: 60s
      retries: 5

  adminer:
    container_name: adminer
    restart: unless-stopped
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: ${DB_NAME}
      ADMINER_DESIGN: 'pepa-linha'
    depends_on:
      - postgres

  rasa:
    container_name: rasa
    restart: unless-stopped
    image: rasa/rasa:latest-full
    volumes:
      - ./../rasa:/app
    ports:
      - '5005:5005'
      - '5010:5010'
    environment:
      SQLALCHEMY_SILENCE_UBER_WARNING: 1
    command:
      - run
      - --enable-api
    depends_on:
      - nginx
      - postgres
    links:
      - nginx
      - postgres

  rasa-sdk:
    container_name: rasa-sdk
    restart: unless-stopped
    image: rasa/rasa-sdk:latest
    ports:
      - '5055:5055'
    volumes:
      - ./../rasa/actions:/app/actions
    depends_on:
      - rasa
      - postgres
    links:
      - rasa
      - postgres

  rasa-duckling:
    container_name: rasa-duckling
    restart: unless-stopped
    image: rasa/duckling:latest
    ports:
      - '8000:8000'
    depends_on:
      - rasa
      - rasa-sdk
    links:
      - rasa
      - rasa-sdk
