version: "3"

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./../src:/var/www/html
      - ./web/config/nginx.conf:/etc/nginx/nginx.conf
      - ./web/ssl/certs:/etc/nginx/ssl
      - ./web/logs:/var/log/nginx
    ports:
      - '8888:80'
      - '443:443'
    depends_on:
      - mysql
      - php
    links:
      - mysql
      - php
  php:
    container_name: php
    restart: unless-stopped
    build:
      context: ./../
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./../src/:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:latest
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
      - ./database/backup:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - '6603:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-p ${DB_PASS}']
      retries: 3
      timeout: 5s
    env_file:
      - ./.env