version: "3.7"

services:

  ###########################
  # N G I N X               #
  ###########################

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.25.1-alpine
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - ./web/log/nginx:/var/log/nginx
      - ./web/nginx/config/fragments:/etc/nginx/fragments
      - ./web/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./web/nginx/ssl/certs:/etc/nginx/ssl
      - ./../src:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - mysql
      - php
      - phpmyadmin
      - jenkins

  ###########################
  # P H P                   #
  ###########################

  php:
    container_name: php
    restart: unless-stopped
    build:
      context: ./../
      dockerfile: ./docker/web/php/Dockerfile
    volumes:
      - ./web/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./web/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./../src:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql

  ###########################
  # D A T A B A S E         #
  ###########################

  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:latest
    volumes:
      - ./database/backup:/var/lib/mysql
      - ./database/config/my.cnf:/etc/my.cnf
      - ./database/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "6603:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p ${DB_PASS}" ]
      retries: 3
      timeout: 5s

  ###########################
  # P H P M Y A D M I N     #
  ###########################

  phpmyadmin:
    container_name: phpmyadmin
    restart: unless-stopped
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASS}
    depends_on:
      - mysql

  ###########################
  # J E N K I N S           #
  ###########################

  jenkins:
    container_name: jenkins
    restart: unless-stopped
    image: jenkins/jenkins:lts-alpine
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "50000:50000"